In [1]:
import os
import requests
import time
import re
from tqdm.auto import tqdm
from dotenv import load_dotenv
import pandas as pd
from pathlib import Path

# langchain
from langchain_chroma import Chroma
from langchain_core.documents import Document
from langchain_huggingface import HuggingFaceEmbeddings

# Load .env into the environment variables block of the memory
load_dotenv()

True

### Data Acquisition

In [2]:
base_url = "https://api.themoviedb.org/3/"

In [3]:
path = "../data/raw/movies_data.parquet"

def fetch_movie_data(base_url, data_folder_path, pages=50):
  if os.path.exists(data_folder_path):
      return pd.read_parquet(data_folder_path)
    
  discover_endpoint = "discover/movie"

  headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjMDEyZDNlOGFiZWZhYTU3M2U1YjhkZGQ3MWFhYmU1MiIsIm5iZiI6MTc3MzE3MjQ4NS43MDg5OTk5LCJzdWIiOiI2OWIwNzcwNTJiNmFmZjZkMzcxMWVhYjIiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.yQJPjdE-OtV-anwg9AhGGBhR6605TmhCe_AJLeL-QWI"
  }

  data = []

  # Get the Ids of popular movies
  for page in tqdm(range(1, pages+1), desc="Fetching movie IDs"):

    movie_params = {
        "vote_count.gte":1000,
        "page":page,
        "sort_by":"popularity.desc"
    }

    response = requests.get(base_url+discover_endpoint, headers=headers, params=movie_params).json()
    data.extend([{"id":movie["id"]} for movie in response['results']])

  print(f"Fetched the Ids of {len(data)} movies")

  # Get details of each movie
  for movie in tqdm(data, desc="Fetching movie details"):
    details_endpoint = f"movie/{movie['id']}"

    try:
      response = requests.get(base_url+details_endpoint, headers=headers).json()

    except Exception as e:
      print(f"Error fetching the movie details :{e}, ID : {movie['id']}")
      continue

    movie['genres'] = ",".join([genre["name"] for genre in response['genres']])
    movie['Duration'] = response['runtime']
    movie['Year_of_release'] = response["release_date"].split('-')[0]
    movie['Title'] = response['title']
    movie['Rating'] = response['vote_average']
    movie['Plot'] = response['overview']

    # Get cast and crew details
    credits_endpoint = f"movie/{movie['id']}/credits"

    try:
      response = requests.get(base_url+credits_endpoint, headers=headers).json()

    except Exception as e:
      print(f"Error fetching the movie details :{e}, ID : {movie['id']}")
      continue

    # Actors'/Acresses' names
    members = [member['name'] for member in response['cast'] if member["known_for_department"]=="Acting"]
    movie['Cast'] = ",".join(set(members[:5]))

    # Directors' names
    directors = {member['name'] for member in response['crew'] if member["known_for_department"]=="Directing"}
    movie['Directors'] = ",".join(directors)

    time.sleep(0.1)
	
  
  df = pd.DataFrame(data)
  # Create the directory if doesn't exist
  Path(data_folder_path).parent.mkdir(parents=True, exist_ok=True)
  df.to_parquet(data_folder_path)
    
  return df

In [4]:
df = fetch_movie_data(base_url, path)

#### Description of features in the dataset
-

In [5]:
df.sample(5)

,id,genres,Duration,Year_of_release,Title,Rating,Plot,Cast,Directors
902,1538,"Drama,Crime,Thriller",120,2004,Collateral,7.241,Cab driver Max picks up a man who offers him $...,"Mark Ruffalo,Tom Cruise,Jamie Foxx,Javier Bard...","Sydney Gilner,Michael Waxman,Harvey Lowry,Carl..."
175,12444,"Adventure,Fantasy",146,2010,Harry Potter and the Deathly Hallows: Part 1,7.734,"Harry, Ron and Hermione walk away from their l...","Helena Bonham Carter,Daniel Radcliffe,Toby Jon...","Jamie Christopher,Stephen Woolfenden,David Yat..."
170,49026,"Action,Crime,Drama,Thriller",165,2012,The Dark Knight Rises,7.792,Following the death of District Attorney Harve...,"Gary Oldman,Tom Hardy,Joseph Gordon-Levitt,Chr...","Boman Modine,Nilo Otero,Sid Karne,Matthew Reed..."
750,225886,Comedy,94,2014,Sex Tape,5.408,"When Jay and Annie first got together, their r...","Rob Lowe,Cameron Diaz,Jason Segel,Ellie Kemper...","Jake Kasdan,Anne Rapp"
963,2108,"Comedy,Drama",98,1985,The Breakfast Club,7.724,Five high school students from different walks...,"Ally Sheedy,Molly Ringwald,Anthony Michael Hal...","Robert P. Cohen,John C. Chulay,Bob Forrest,Jam..."

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1000 non-null   int64
 1   genres           1000 non-null   str
 2   Duration         1000 non-null   int64
 3   Year_of_release  1000 non-null   str
 4   Title            1000 non-null   str
 5   Rating           1000 non-null   float64
 6   Plot             1000 non-null   str
 7   Cast             1000 non-null   str
 8   Directors        1000 non-null   str
dtypes: float64(1), int64(2), str(6)
memory usage: 559.0 KB

In [7]:
df.describe(include='all')

,id,genres,Duration,Year_of_release,Title,Rating,Plot,Cast,Directors
count,1.000000e+03,1000,1000.000000,1000,1000,1000.000000,1000,1000,1000
unique,NaN,461,NaN,72,983,NaN,999,983,993
top,NaN,"Action,Adventure,Science Fiction",NaN,2025,Dune,NaN,"Tony Lip, a bouncer in 1962, is hired to drive...","Jennifer Lawrence,Woody Harrelson,Elizabeth Ba...",
freq,NaN,36,NaN,53,2,NaN,2,4,4
mean,2.541548e+05,NaN,120.669000,NaN,NaN,7.188406,NaN,NaN,NaN
std,3.276499e+05,NaN,24.566582,NaN,NaN,0.675585,NaN,NaN,NaN
min,1.100000e+01,NaN,74.000000,NaN,NaN,4.324000,NaN,NaN,NaN
25%,2.215500e+03,NaN,103.000000,NaN,NaN,6.725000,NaN,NaN,NaN
50%,7.214750e+04,NaN,117.500000,NaN,NaN,7.224500,NaN,NaN,NaN
75%,4.213905e+05,NaN,132.250000,NaN,NaN,7.679000,NaN,NaN,NaN
max,1.376434e+06,NaN,253.000000,NaN,NaN,8.717000,NaN,NaN,NaN

In [8]:
# Get the max length of a plot in the dataset
max_len_plot = df['Plot'].str.split().str.len().max()
max_len_plot

np.int64(146)

### EDA

### Data Preprocessing

In [9]:
# Prepare the data for embedding generation

path = "../data/preprocessed/movies_data.parquet"
def preprocess_data(df, data_folder_path):
  if os.path.exists(data_folder_path):
      return pd.read_parquet(data_folder_path)
      
  # Drop duplicate rows and reset row indices.
  df = df.drop_duplicates()
  df = df.reset_index(drop=True)

  # Combine the text info for embedding generation.
  df['combined_text_info'] = "genres:" + df['genres'] + ", title:" + df['Title'] + ", plot:" + df['Plot'] + ", cast:" + df['Cast'] + ", directors:" + df['Directors']
  df['combined_text_info'] = df['combined_text_info'].apply(lambda x : re.sub(r'\s+'," ", x)) # Remove extra white spaces

  # Normalize the case in all the text fields.
  text_fields = df.select_dtypes(exclude='number').columns
  df.loc[:, text_fields] = df[text_fields].apply(lambda x : x.str.lower())

  # Create the directory if it doesn't already exist.
  Path(data_folder_path).parent.mkdir(parents=True, exist_ok=True)    
  df.to_parquet(data_folder_path)
  return df

df = preprocess_data(df, path)
df.sample(5)

,id,genres,Duration,Year_of_release,Title,Rating,Plot,Cast,Directors,combined_text_info
790,1136867,"romance,drama",116,2025,materialists,6.358,"a young, ambitious new york city matchmaker fi...","dakota johnson,zoë winters,pedro pascal,chris ...","mauricio calderón,sofia coppola,halina reijn,b...","genres:romance,drama, title:materialists, plot..."
298,102899,"science fiction,adventure,action",117,2015,ant-man,7.066,armed with the astonishing ability to shrink i...,"michael douglas,evangeline lilly,bobby cannava...","adam mckay,nick satriano,riley flanagan,joe co...","genres:science fiction,adventure,action, title..."
825,268,"fantasy,action,crime",126,1989,batman,7.229,having witnessed his parents' brutal murder as...,"jack nicholson,robert wuhl,kim basinger,pat hi...","derek cracknell,peter macdonald,melvin lind,st...","genres:fantasy,action,crime, title:batman, plo..."
822,713704,"horror,thriller",96,2023,evil dead rise,6.914,a reunion between two estranged sisters gets c...,"nell fisher,gabrielle echols,alyssa sutherland...","craig wilson,sam raimi,daire glynn,darren mack...","genres:horror,thriller, title:evil dead rise, ..."
817,1635,"action,thriller,science fiction,adventure",136,2005,the island,6.700,"in 2019, lincoln six-echo is a resident of a s...","scarlett johansson,ewan mcgregor,steve buscemi...","steve battaglia,michael bay,douglas dean iii,b...","genres:action,thriller,science fiction,adventu..."

### Embedding Generation

There are 3 ways to go about this:
- One vector per text field

- Combine the text info into one single string and generate one vector per movie

- Hybrid approach: Keep the text fields as such and also include a combined text field. Use the combined text field to do semantic search and the separate text fields for metadata filtering.

Example case<br>
  user query: "Suggest horror movies directed by James Van"<br>
  Semantic search will fetch all the horror movies and those results can be refined using the concrete info about the director mentioned in the user query.

In [10]:
def create_docs(df):
    docs = []

    # Iterate through the rows and create one document per row.
    for _, row in tqdm(df.iterrows(), total=len(df), desc="Creating Documents"):
        doc = Document(
            page_content=row['combined_text_info'],
            metadata={
                'genres':row['genres'].split(','),
                'Duration':row['Duration'],
                'Year_of_release':row['Year_of_release'],
                'Title':row['Title'],
                'Rating':row['Rating'],
                'Cast':row['Cast'].split(','),
                'Directors':row['Directors'].split(',')
            }
        )

        docs.append(doc)

    return docs

In [11]:
model = HuggingFaceEndpointEmbeddings(model="BAAI/bge-m3", 
                              huggingfacehub_api_token=os.getenv('HF_TOKEN')
                            )

path = "../vector_db"
def initiate_vector_db(embedding_model, vector_db_path, docs):

    # If the vector database is already created just connect to it. 
    if os.path.exists(vector_db_path):
        print("Connect to the existing vectorDB...")
        vector_db = Chroma(
            embedding_function=embedding_model,
            persist_directory=vector_db_path,
            collection_name='movies'
        )    

    # Create a new vector database and ingest all the docs into it.
    else:    
        print("Creating a new vectorDB....")
        vector_db = Chroma.from_documents(
            documents=docs,
            embedding=embedding_model,
            persist_directory=vector_db_path,
            collection_name='movies'
        )
        
    return vector_db

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

In [12]:
docs = create_docs(df)
initiate_vector_db(model, path, docs)

Creating Documents:   0%|          | 0/999 [00:00<?, ?it/s]

Connect to the existing vectorDB...