In [ ]:
import os
import requests
import time
import re
from dotenv import load_dotenv
import pandas as pd

### Data Acquisition

In [ ]:
load_dotenv()
api_key = os.getenv('TMDB_API_KEY')

if api_key:
    print("API key is successfully loaded")
else:
    print("Error loading the api key")

API key is successfully loaded

In [ ]:
base_url = "https://api.themoviedb.org/3/"

In [ ]:
def fetch_movie_data(base_url, pages=50):
  discover_endpoint = "discover/movie"

  headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjMDEyZDNlOGFiZWZhYTU3M2U1YjhkZGQ3MWFhYmU1MiIsIm5iZiI6MTc3MzE3MjQ4NS43MDg5OTk5LCJzdWIiOiI2OWIwNzcwNTJiNmFmZjZkMzcxMWVhYjIiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.yQJPjdE-OtV-anwg9AhGGBhR6605TmhCe_AJLeL-QWI"
  }

  data = []

  # Get the Ids of popular movies
  for page in range(1, pages+1):

    movie_params = {
        "vote_count.gte":1000,
        "page":page,
        "sort_by":"popularity.desc"
    }

    response = requests.get(base_url+discover_endpoint, headers=headers, params=movie_params).json()
    data.extend([{"id":movie["id"]} for movie in response['results']])

  print(f"Fetched the Ids of {len(data)} movies")

  # Get details of each movie
  for movie in data:
    details_endpoint = f"movie/{movie['id']}"

    try:
      response = requests.get(base_url+details_endpoint, headers=headers).json()

    except Exception as e:
      print(f"Error fetching the movie details :{e}, ID : {movie['id']}")
      continue

    movie['genres'] = ",".join([genre["name"] for genre in response['genres']])
    movie['Duration'] = response['runtime']
    movie['Year_of_release'] = response["release_date"].split('-')[0]
    movie['Title'] = response['title']
    movie['Rating'] = response['vote_average']
    movie['Plot'] = response['overview']

    # Get cast and crew details
    credits_endpoint = f"movie/{movie["id"]}/credits"

    try:
      response = requests.get(base_url+credits_endpoint, headers=headers).json()

    except Exception as e:
      print(f"Error fetching the movie details :{e}, ID : {movie['id']}")
      continue

    # Actors'/Acresses' names
    members = [member['name'] for member in response['cast'] if member["known_for_department"]=="Acting"]
    movie['Cast'] = ",".join(set(members[:5]))

    # Directors' names
    directors = {member['name'] for member in response['crew'] if member["known_for_department"]=="Directing"}
    movie['Directors'] = ",".join(directors)

  return data

In [ ]:
movies_dataset = fetch_movie_data(base_url)

Fetched the Ids of 1000 movies

#### Description of features in the dataset
-

In [ ]:
df = pd.DataFrame(movies_dataset)

In [ ]:
df.sample(5)

,id,genres,Duration,Year_of_release,Title,Rating,Plot,Cast,Directors
528,4488,Horror,95,1980,Friday the 13th,6.401,Camp counselors are stalked and murdered by an...,"Kevin Bacon,Adrienne King,Jeannine Taylor,Bets...","Steve Miner,Ted Lowry,Cindy Veazey,Martin Kitr..."
338,10192,"Comedy,Adventure,Fantasy,Animation,Family",93,2010,Shrek Forever After,6.400,"A midlife-crisis burdened Shrek, longing for t...","Antonio Banderas,Cameron Diaz,Mike Myers,Walt ...","Josh LaBrot,Mike Mitchell,Maggie Kang"
240,507086,"Adventure,Action,Science Fiction",147,2022,Jurassic World Dominion,6.600,"Four years after Isla Nublar was destroyed, di...","Laura Dern,Sam Neill,Chris Pratt,Jeff Goldblum...","Fraser Fennell-Ball,Charlie Endean,Liberty Che..."
413,772,"Comedy,Family,Adventure",120,1992,Home Alone 2: Lost in New York,6.782,"Instead of flying to Florida with his folks, K...","Catherine O'Hara,Daniel Stern,Macaulay Culkin,...","Geoffrey Hansen,Christo Morse,James Giovannett..."
776,180,"Science Fiction,Action,Thriller",145,2002,Minority Report,7.351,John Anderton is a top 'Precrime' cop in the l...,"Kathryn Morris,Max von Sydow,Tom Cruise,Samant...","Robert Rooy,Ana Maria Quintana,Sergio Mimica-G..."

### Preprocessing

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1000 non-null   int64
 1   genres           1000 non-null   object
 2   Duration         1000 non-null   int64
 3   Year_of_release  1000 non-null   object
 4   Title            1000 non-null   object
 5   Rating           1000 non-null   float64
 6   Plot             1000 non-null   object
 7   Cast             1000 non-null   object
 8   Directors        1000 non-null   object
dtypes: float64(1), int64(2), object(6)
memory usage: 70.4+ KB

In [ ]:
# Check for duplicate rows and drop them if any.
df.duplicated().sum()

np.int64(1)

In [ ]:
df.describe(include='all')

,id,genres,Duration,Year_of_release,Title,Rating,Plot,Cast,Directors
count,1.000000e+03,1000,1000.000000,1000,1000,1000.000000,1000,1000,1000
unique,NaN,459,NaN,74,982,NaN,999,983,995
top,NaN,"Action,Adventure,Science Fiction",NaN,2025,Superman,NaN,Three years after Jurassic World was destroyed...,"Liam Hemsworth,Elizabeth Banks,Jennifer Lawren...",
freq,NaN,33,NaN,54,2,NaN,2,4,3
mean,2.553315e+05,NaN,121.097000,NaN,NaN,7.186079,NaN,NaN,NaN
std,3.336702e+05,NaN,24.386149,NaN,NaN,0.677519,NaN,NaN,NaN
min,1.100000e+01,NaN,74.000000,NaN,NaN,4.323000,NaN,NaN,NaN
25%,1.929250e+03,NaN,104.750000,NaN,NaN,6.724750,NaN,NaN,NaN
50%,6.871950e+04,NaN,118.000000,NaN,NaN,7.228500,NaN,NaN,NaN
75%,4.247162e+05,NaN,133.000000,NaN,NaN,7.677500,NaN,NaN,NaN
max,1.376434e+06,NaN,253.000000,NaN,NaN,8.717000,NaN,NaN,NaN

In [ ]:
# Get the max length of a plot in the dataset
max_len_plot = df['Plot'].str.split().str.len().max()
max_len_plot

146

In [ ]:
# Prepare the data for embedding generation

def preprocess_data(df):
  # Drop duplicate rows and reset row indices.
  df = df.drop_duplicates()
  df = df.reset_index(drop=True)

  # Combine the text info for embedding generation.
  df['combined_text_info'] = "genres:" + df['genres'] + ", title:" + df['Title'] + ", plot:" + df['Plot'] + ", cast:" + df['Cast'] + ", directors:" + df['Directors']
  df['combined_text_info'] = df['combined_text_info'].apply(lambda x : re.sub(r'\s+'," ", x)) # Remove extra white spaces

  # Normalize the case in all the text fields.
  text_fields = df.select_dtypes(exclude='number').columns
  df.loc[:, text_fields] = df[text_fields].apply(lambda x : x.str.lower())

  return df

df = preprocess_data(df)
df.sample(5)

,id,genres,Duration,Year_of_release,Title,Rating,Plot,Cast,Directors,combined_text_info
516,273481,"action,crime,thriller",122,2015,sicario,7.417,an idealistic fbi agent is enlisted by a gover...,"emily blunt,josh brolin,benicio del toro,victo...","stephanie tull,karen davis,eric calatayud,deni...","genres:action,crime,thriller, title:sicario, p..."
603,194,"comedy,romance",122,2001,amélie,7.917,"at a tiny parisian café, the adorable yet pain...","mathieu kassovitz,serge merlin,rufus,audrey ta...","christophe vassort,sylvain bressollette,jean-p...","genres:comedy,romance, title:amélie, plot:at a..."
22,634649,"action,adventure,science fiction",148,2021,spider-man: no way home,7.933,peter parker is unmasked and no longer able to...,"benedict cumberbatch,jon favreau,jacob batalon...","kera dacy,jon watts,brian avery galligan,david...","genres:action,adventure,science fiction, title..."
635,402,"thriller,mystery",128,1992,basic instinct,6.935,"catherine, a novelist with an insatiable sexua...","sharon stone,jeanne tripplehorn,denis arndt,ge...","catherine marie mcdonald,trudy ramirez,paul ve...","genres:thriller,mystery, title:basic instinct,..."
640,36643,"adventure,action,thriller",128,1999,the world is not enough,6.284,"greed, revenge, world dominance and high-tech ...","denise richards,sophie marceau,robert carlyle,...","daniel kleinman,michael apted,nikki clapp,deni...","genres:adventure,action,thriller, title:the wo..."

### EDA

### Embedding Generation

There are 3 ways to go about this:
- One vector per text field

- Combine the text info into one single string and generate one vector per movie

- Hybrid approach: Keep the text fields as such and also include a combined text field. Use the combined text field to do semantic search and the separate text fields for metadata filtering.

Example case<br>
  user query: "Suggest horror movies directed by James Van"<br>
  Semantic search will fetch all the horror movies and those results can be refined using the concrete info about the director mentioned in the user query.